/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/nobac.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tapa.geometry}
        material={materials.main}
        position={[8.414, 17.717, -44.842]}
        rotation={[0.368, -0.359, 0.134]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cristal.geometry}
          material={materials.glass}
          position={[0.002, 14.08, 46.132]}
          rotation={[0.001, 0, 0]}
          scale={39.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve002.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve003.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve004.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve005.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve006.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve008.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve009.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve010.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve011.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve012.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve013.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve014.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve015.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve016.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve017.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve018.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve019.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve020.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve021.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve022.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve023.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve024.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve026.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve027.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve028.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve029.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve030.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve031.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve032.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve033.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve034.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve035.geometry}
          material={materials["SVGMat.001"]}
          position={[-18.999, 16.916, 79.748]}
          scale={352.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TM.geometry}
          material={nodes.TM.material}
          position={[18.583, 16.495, 70.266]}
          scale={0.085}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paredes.geometry}
        material={materials.main}
        position={[-9.176, -8.413, -3.13]}
        rotation={[0.379, -0.358, 0.139]}
        scale={[47, 21.3, 47]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base001.geometry}
          material={materials.Material}
          position={[0.013, -0.562, -0.097]}
          scale={1.003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base_de_goma.geometry}
          material={materials["Material.001"]}
          position={[0.765, 0.218, 0.472]}
          scale={[0.021, 0.052, 0.021]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boton001.geometry}
          material={materials.main}
          position={[0.013, 0.261, 0.91]}
          scale={[0.021, 0.046, 0.021]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boton_encendido.geometry}
          material={materials["Material.003"]}
          position={[0.537, 0.754, -0.598]}
          scale={[0.03, 0.103, 0.031]}
        />
        <group position={[0.226, 0.44, -0.684]} scale={[0.021, 0.047, 0.021]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials.main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_1.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group position={[0.013, -0.592, -0.1]} scale={[0.441, 0.04, 0.441]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008.geometry}
            material={materials.main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_1.geometry}
            material={materials.iman}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.espejo.geometry}
          material={materials["Light Metal"]}
          position={[0.013, -0.392, -0.325]}
          scale={[-0.946, -2.146, -0.982]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fondo_puerto.geometry}
          material={materials["Material.002"]}
          position={[-0.925, 0.029, -0.53]}
          scale={[0.021, 0.047, 0.021]}
        />
        <group position={[0.016, -0.011, -0.038]} scale={[0.021, 0.047, 0.021]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.leds}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metal_puerto.geometry}
          material={materials["Light Metal"]}
          position={[-0.933, 0.029, -0.53]}
          scale={[0.02, 0.046, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pines_de_carga.geometry}
          material={materials.Brass}
          position={[-0.931, 0.039, -0.502]}
          scale={[0.021, 0.046, 0.021]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.puerto.geometry}
          material={materials["Material.002"]}
          position={[-0.918, 0.038, -0.5]}
          scale={[0.021, 0.176, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soporte_lateral.geometry}
          material={materials.main}
          position={[0.747, 0.181, -0.188]}
          scale={[0.218, 0.687, 0.262]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/nobac.glb");
